mappings:
  UpdateComposer: Sunnysideup\ModuleChecks\BaseCommands\UpdateComposer
  RunCommandLineMethodOnModule: Sunnysideup\ModuleChecks\BaseCommands\RunCommandLineMethodOnModule
  AddFileToModule: Sunnysideup\ModuleChecks\BaseCommands\AddFileToModule
  GeneralMethods: Sunnysideup\ModuleChecks\Api\GeneralMethods
  GitHubApi: Sunnysideup\ModuleChecks\Api\GitHubApi
  AddGitAttributesToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddGitAttributesToModule
  AddGitIgnoreToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddGitIgnoreToModule
  AddHtAccessToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddHtAccessToModule
  AddTravisYmlToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddTravisYmlToModule
  AddEditorConfigToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddEditorConfigToModule
  AddContributingToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddContributingToModule
  AddUserguideMdToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddUserguideMdToModule
  AddSourceReadmeToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddSourceReadmeToModule
  AddLicenceToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddLicenceToModule
  AddScrutinizerYmlToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddScrutinizerYmlToModule
  AddChangeLogToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddChangeLogToModule
  AddTestToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddTestToModule
  AddManifestExcludeToModule: Sunnysideup\ModuleChecks\FilesToAdd\AddManifestExcludeToModule
  UpdateLicense: Sunnysideup\ModuleChecks\ComposerJson\UpdateLicense
  UpdataModuleType: Sunnysideup\ModuleChecks\ComposerJson\UpdataModuleType
  CheckOrAddExtraArray: Sunnysideup\ModuleChecks\ComposerJson\CheckOrAddExtraArray
  ModuleConfigInterface: Sunnysideup\ModuleChecks\Interface\ModuleConfigInterface
  FixPSR2: Sunnysideup\ModuleChecks\ShellCommands\FixPSR2
  SetPermissions: Sunnysideup\ModuleChecks\ShellCommands\SetPermissions
  RemoveOrig: Sunnysideup\ModuleChecks\ShellCommands\RemoveOrig
  RemoveSVN: Sunnysideup\ModuleChecks\ShellCommands\RemoveSVN
  RemoveAPI: Sunnysideup\ModuleChecks\ShellCommands\RemoveAPI
  FixConfigBasics: Sunnysideup\ModuleChecks\ShellCommands\FixConfigBasics
  ConfigYML: Sunnysideup\ModuleChecks\Api\ConfigYML
  ComposerJson: Sunnysideup\ModuleChecks\Api\ComposerJsonClass
  GitHubModule: Sunnysideup\ModuleChecks\Model\GitHubModule
  ModuleChecks: Sunnysideup\ModuleChecks\Tasks\ModuleChecks
  UpdateModules: Sunnysideup\ModuleChecks\Tasks\UpdateModules
